server:
  port: 3333

 #配置web页面入口
magic-api:
  web: /magic/web

# database
db:
  conn:
    str: useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
# 默认主数据源
spring:
  datasource:
      jdbc-url: jdbc:mysql://localhost:3306/magic-api?${db.conn.str}
      username: root
      password: mysql
      driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.magic.username=root
#spring.datasource.magic.password=
#spring.datasource.magic.driver-class-name=com.mysql.cj.jdbc.Driver
# pm数据源
  pm-datasource:
    jdbc-url: jdbc:mysql://localhost:3306/magic-api?${db.conn.str}
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.pm.jdbc-url=jdbc:mysql://localhost:3306/pm?${db.conn.str}
#spring.datasource.pm.username=root
#spring.datasource.pm.password=
#spring.datasource.pm.driver-class-name=com.mysql.cj.jdbc.Driver
